export const PUSH_PATH_HISTORY = 'PUSH_PATH_HISTORY'

export const CLEAR_DIRECT = 'CLEAR_DIRECT'
export const CLEAR_KEYWORDS = 'CLEAR_KEYWORDS'
// export const CLEAR_FASTLINKS = 'CLEAR_FASTLINKS'

export const SET_DIRECT_INDEX = 'SET_DIRECT_INDEX'
export const SET_DIRECT = 'SET_DIRECT'

export const SET_KEYWORDS_TEMPLATE = 'SET_KEYWORDS_TEMPLATE'
export const SET_KEYWORDS = 'SET_KEYWORDS'

export const SET_FASTLINKS_TEMPLATE = 'SET_FASTLINKS_TEMPLATE'
export const SET_FASTLINKS = 'SET_FASTLINKS'