export const PUSH_PATH_HISTORY = 'PUSH_PATH_HISTORY'

export const CLEAR_DIRECT = 'CLEAR_DIRECT'
export const CLEAR_KEYWORDS = 'CLEAR_KEYWORDS'
export const CLEAR_FASTLINKS = 'CLEAR_FASTLINKS'

export const CLEAR_REDO_STATES = 'CLEAR_REDO_STATES'

export const SET_DIRECT_INDEX = 'SET_DIRECT_INDEX'
export const SET_DIRECT = 'SET_DIRECT'

export const SET_KEYWORDS_TEMPLATE = 'SET_KEYWORDS_TEMPLATE'
export const SET_KEYWORDS = 'SET_KEYWORDS'

export const SET_FASTLINKS_TEMPLATE = 'SET_FASTLINKS_TEMPLATE'
export const SET_FASTLINKS = 'SET_FASTLINKS'

export const UTM_MARK_MAIN = 'UTM_MARK_MAIN'
export const UTM_MARK_FAST = 'UTM_MARK_FAST'

